# Generated by Django 3.0.6 on 2020-05-17 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, verbose_name="Name")),
            ],
            options={"verbose_name": "Brand", "verbose_name_plural": "Brands", "db_table": "brand"},
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
            ],
            options={"verbose_name": "Category", "verbose_name_plural": "Categories", "db_table": "category"},
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, verbose_name="Name")),
                ("phone", models.CharField(max_length=20, verbose_name="Phone")),
                ("notes", models.TextField(blank=True, max_length=500, null=True, verbose_name="Notes")),
            ],
            options={"verbose_name": "Supplier", "verbose_name_plural": "Suppliers", "db_table": "supplier"},
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=250, verbose_name="Name")),
                ("product_code", models.CharField(max_length=100, verbose_name="Product code")),
                ("margin", models.FloatField(verbose_name="Margin")),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="shop.Brand", verbose_name="brand"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="shop.Category", verbose_name="category"
                    ),
                ),
            ],
            options={"verbose_name": "Product", "verbose_name_plural": "Products", "db_table": "product"},
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_date", models.DateTimeField(auto_now=True, verbose_name="Date created")),
                ("updated_date", models.DateTimeField(auto_now_add=True, verbose_name="Date updated")),
                ("cost", models.FloatField(verbose_name="Cost")),
                ("selling_price", models.FloatField(blank=True, null=True, verbose_name="Selling price")),
                ("sold_date", models.DateTimeField(blank=True, null=True, verbose_name="Date of the sale")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="shop.Product",
                        verbose_name="product",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="shop.Supplier",
                        verbose_name="supplier",
                    ),
                ),
            ],
            options={"verbose_name": "Item", "verbose_name_plural": "Items", "db_table": "item"},
        ),
    ]
